-- Create the table to hold our curated demo reports
CREATE TABLE public.demo_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type text NOT NULL UNIQUE, -- 'foundation' or 'gap_analysis'
    content text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL
);

-- Add a comment for clarity
COMMENT ON TABLE public.demo_reports IS 'Stores curated, high-quality reports for a realistic demo mode.';

-- Insert the high-quality Foundation Report example
INSERT INTO public.demo_reports (report_type, content)
VALUES (
    'foundation',
    '# Market Research Pack: AI-Powered Strategic Workforce Optimization Platforms

## Executive Summary

The strategic workforce planning landscape is undergoing a profound transformation, shifting from traditional, reactive Human Capital Management (HCM) systems to sophisticated, AI-driven platforms. This evolution is fueled by organizations'' urgent need to integrate internal talent data with external labor market intelligence, enabling predictive insights for talent acquisition, development, and deployment. The global market for AI in HR was valued at approximately $3.25 billion in 2023 and is projected to reach $15.24 billion by 2030, reflecting a robust 24.8% Compound Annual Growth Rate (CAGR). Talent intelligence software specifically is forecasted to grow from $3.12 billion in 2024 to $8.72 billion by 2033, at a 12.2% CAGR.

Key market drivers include the critical need to automate routine HR tasks (reducing time-to-fill positions by up to 85%), the imperative for skills-based talent management (over 60% of companies prioritize skills analysis), and the power of predictive analytics to forecast needs and reduce turnover (by up to 174%). However, significant headwinds persist, primarily around data privacy and compliance (a barrier for 60-75% of organizations), integration complexity with legacy HR systems, and inherent AI bias concerns (flagged by 25-35%).'
);

-- Insert the high-quality Gap Analysis Report example
INSERT INTO public.demo_reports (report_type, content)
VALUES (
    'gap_analysis',
    '# Strategic Workforce Intelligence Platform Adoption: Depth Report

## Executive Summary

Global enterprises, while recognizing the critical importance of data-driven workforce planning, overwhelmingly prefer leveraging and enhancing existing "good enough" solutions—such as internal BI teams and enhanced Human Capital Management (HCM) analytics—over adopting dedicated Strategic Workforce Intelligence (SWI) platforms. This preference stems from significant barriers including prohibitive costs, complex implementation, organizational readiness gaps, and data quality concerns.

Companies like Google, Microsoft, and IBM exemplify this trend, achieving sophisticated workforce intelligence through internal development and strategic enhancements to their HCM ecosystems. Sector-specific analysis reveals that technology firms often build proprietary solutions, financial services prioritize control due to regulatory demands, healthcare organizations opt for targeted solutions due to budget constraints, and manufacturing firms enhance existing ERP and HCM systems.

Despite a growing market for workforce analytics (projected to reach $5.94 billion by 2032), much of this growth is absorbed by cloud-based analytics enhancements and internal capability building, rather than dedicated platform adoption. Enterprises are increasingly drawn to process mining, cloud-based analytics, and skills-based workforce planning as strategic alternatives, as they offer flexibility, cost-effectiveness, and less organizational disruption.'
);
